set -g default-terminal "Tmux-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"

set -g status-fg white
set -g status-bg colour236 

# border colours
set -g pane-border-style fg=white
set -g pane-active-border-style bg=default

set-option -g default-shell /bin/zsh
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
